### PR TITLE
Keep project repo

### PR DESCRIPTION
**Pull request by ksclarke**
It doesn't hurt to have it on the production machine and the developer needs it on the dev machine.

### CODE REVIEW

**Comment by ksclarke** [comment]
Another option would be to use tags to control what's done for dev vs. prod, etc., if you really wanted to remove it from the production machine.

**Comment by ksclarke** [comment]
And, to help inform your decision, there will be other things that a dev box will want that a production box doesn't necessarily need (to set up a dev .env for instance).

**Comment by hardyoyo** [comment]
+1 for keeping the repo

**Comment by sgurnick** [comment]
@ksclarke and @hardyoyo: It sounds like there might be a misunderstanding (potentially on my part) as to this task to remove the ansible user's check-out of the code.

The goal of this deploy role is that it is only run one time, regardless of what environment it is (e.g. dev, sandbox, test, stage, prod, etc). 

It is my understanding the ansible user should not have any code checked out for itself. This creates a second copy of the code that, in my estimation, becomes superfluous. 

I'm not sure how your dev environments are set-up with respect to doing subsequent deploys, so perhaps this worth a discussion to help my understanding.

**Comment by hardyoyo** [comment]
I believe @ksclarke when he says he needs the code checkout to be left on a dev machine. The answer may be as simple as that he does not wish to check out the code twice. Perhaps we can parameterize this so one can optionally  ask for the cleanup to be skipped, via a variable?

**Comment by ksclarke** [comment]
Yes, Hardy is right. I just want the checked out code on the machine because the developer gets a box that's been created via the ansible roles and doesn't want to then check the code out again manually. While the production machine only uses that code once (to deploy to its final location) the developer will work with that code on an ongoing basis. And, yes, I was suggesting Ansible tagging so that the behavior of leaving the code on the machine could be triggered only when a developer was using the roles to build a dev box. When the code was run as a part of production, no dev tag would be supplied and the code would be removed by the box (this isn't reflected in my PR... the PR was to start the conversation). I'm glad to Slack call, @sgurnick, to talk more about this.

**Comment by sgurnick** [comment]
@ksclarke and @hardyoyo: yes - I think a call to discuss this would be helpful so I can better understand the workflow. I'll reach out to you today or tomorrow and we can review.

**Comment by ksclarke** [comment]
NO NOT MERGE YET. TESTING USE of `always` ANSIBLE TAG.

**Comment by ksclarke** [comment]
Okay, this works for me @sgurnick (keeps or doesn't keep the directory depending on whether I run the playbook with `--skip-tags always` or not. It's now ready to merge whenever you get a chance to confirm that it works for you.

**Pull request merged**
